/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/series/featured-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Featured Config */
        get: operations["get_featured_config_series_featured_config_get"];
        put?: never;
        /** Update Featured Config */
        post: operations["update_featured_config_series_featured_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/hero-featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hero Featured */
        get: operations["get_hero_featured_series_hero_featured_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_series_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recommendations
         * @description Cold-start recommendations, for signed-out visitors.
         */
        get: operations["get_recommendations_series_recommendations_get"];
        put?: never;
        /**
         * Get Personalized Recommendations
         * @description Personalized recommendations from client-supplied signals.
         *
         *     A POST because the signal lists can be long; nothing is stored.
         */
        post: operations["get_personalized_recommendations_series_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Series */
        get: operations["read_series_series__get"];
        put?: never;
        /** Create Series */
        post: operations["create_series_series__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/by-ids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Series By Ids
         * @description Hydrate a set of series by id, in one round trip.
         *
         *     Firestore stores only the series id for likes / my-list / history, so the
         *     client needs to resolve them against the catalog. Unlike /series/{id}, this
         *     does NOT increment views_count — these are list renders, not views, and
         *     counting them would inflate the popularity used by the hero rotation.
         */
        get: operations["read_series_by_ids_series_by_ids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_ident}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Series Detail */
        get: operations["read_series_detail_series__series_ident__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_ident}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Episodes */
        get: operations["read_episodes_series__series_ident__episodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Actors */
        get: operations["read_actors_actors__get"];
        put?: never;
        /** Create Actor */
        post: operations["create_actor_actors__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/actors/{actor_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Actor */
        get: operations["read_actor_actors__actor_id__get"];
        /** Update Actor */
        put: operations["update_actor_actors__actor_id__put"];
        post?: never;
        /** Delete Actor */
        delete: operations["delete_actor_actors__actor_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_id}/feature": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Featured Series */
        post: operations["set_featured_series_series__series_id__feature_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Series */
        put: operations["update_series_series__series_id__put"];
        post?: never;
        /** Delete Series */
        delete: operations["delete_series_series__series_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/{series_id}/episodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Episode */
        post: operations["create_episode_series__series_id__episodes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/series/episodes/{episode_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Episode */
        put: operations["update_episode_series_episodes__episode_id__put"];
        post?: never;
        /** Delete Episode */
        delete: operations["delete_episode_series_episodes__episode_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Current User
         * @description Echo back the verified identity.
         *
         *     The client already knows who it is from the Firebase SDK; what it cannot
         *     know on its own is whether this backend considers it an administrator, since
         *     that is decided server-side.
         */
        get: operations["read_current_user_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Actor */
        Actor: {
            /** Name */
            name: string;
            /** Real Name */
            real_name?: string | null;
            /**
             * Gender
             * @default Female
             */
            gender: string;
            /** Image Url */
            image_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Social Media */
            social_media?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ActorCreate */
        ActorCreate: {
            /** Name */
            name: string;
            /** Real Name */
            real_name?: string | null;
            /**
             * Gender
             * @default Female
             */
            gender: string;
            /** Image Url */
            image_url?: string | null;
            /** Bio */
            bio?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Social Media */
            social_media?: string | null;
        };
        /** Episode */
        Episode: {
            /** Title */
            title: string;
            /** Episode Number */
            episode_number: number;
            /**
             * Season Number
             * @default 1
             */
            season_number: number | null;
            /** Embed Url 1 */
            embed_url_1?: string | null;
            /** Embed Url 2 */
            embed_url_2?: string | null;
            /** Download Link */
            download_link?: string | null;
            /** External Link */
            external_link?: string | null;
            /** Drive Link */
            drive_link?: string | null;
            /** Mega Link */
            mega_link?: string | null;
            /** Mediafire Link */
            mediafire_link?: string | null;
            /** Pixeldrain Link */
            pixeldrain_link?: string | null;
            /** Youtube Link */
            youtube_link?: string | null;
            /** Id */
            id: number;
            /** Series Id */
            series_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EpisodeCreate */
        EpisodeCreate: {
            /** Title */
            title: string;
            /** Episode Number */
            episode_number: number;
            /**
             * Season Number
             * @default 1
             */
            season_number: number | null;
            /** Embed Url 1 */
            embed_url_1?: string | null;
            /** Embed Url 2 */
            embed_url_2?: string | null;
            /** Download Link */
            download_link?: string | null;
            /** External Link */
            external_link?: string | null;
            /** Drive Link */
            drive_link?: string | null;
            /** Mega Link */
            mega_link?: string | null;
            /** Mediafire Link */
            mediafire_link?: string | null;
            /** Pixeldrain Link */
            pixeldrain_link?: string | null;
            /** Youtube Link */
            youtube_link?: string | null;
        };
        /** FeaturedConfigCreate */
        FeaturedConfigCreate: {
            /**
             * Mode
             * @default MOST_WATCHED
             */
            mode: string;
            /**
             * Rotate Interval Minutes
             * @default 60
             */
            rotate_interval_minutes: number;
            /** Manual Series Id */
            manual_series_id?: number | null;
        };
        /** FeaturedConfigResponse */
        FeaturedConfigResponse: {
            /**
             * Mode
             * @default MOST_WATCHED
             */
            mode: string;
            /**
             * Rotate Interval Minutes
             * @default 60
             */
            rotate_interval_minutes: number;
            /** Manual Series Id */
            manual_series_id?: number | null;
            /** Id */
            id: number;
            manual_series?: components["schemas"]["Series"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * RecommendationSignals
         * @description Taste signals the client reads from its own Firestore data.
         */
        RecommendationSignals: {
            /**
             * Watched Ids
             * @default []
             */
            watched_ids: number[];
            /**
             * Liked Ids
             * @default []
             */
            liked_ids: number[];
            /**
             * Listed Ids
             * @default []
             */
            listed_ids: number[];
            /** Recent Series Id */
            recent_series_id?: number | null;
        };
        /** Series */
        Series: {
            /** Title */
            title: string;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /** Banner Image */
            banner_image?: string | null;
            /** Genre */
            genre: string;
            /**
             * Type
             * @default Series
             */
            type: string;
            /** Country */
            country: string;
            /** Status */
            status: string;
            /** Release Year */
            release_year: number;
            /** Trailer Url */
            trailer_url?: string | null;
            /**
             * Feature Type
             * @default TRAILER
             */
            feature_type: string | null;
            /** Cast */
            cast?: string | null;
            /** Drive Link */
            drive_link?: string | null;
            /** Mega Link */
            mega_link?: string | null;
            /** Mediafire Link */
            mediafire_link?: string | null;
            /** Pixeldrain Link */
            pixeldrain_link?: string | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Views Count
             * @default 0
             */
            views_count: number | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SeriesCreate */
        SeriesCreate: {
            /** Title */
            title: string;
            /** Slug */
            slug?: string | null;
            /** Description */
            description?: string | null;
            /** Cover Image */
            cover_image?: string | null;
            /** Banner Image */
            banner_image?: string | null;
            /** Genre */
            genre: string;
            /**
             * Type
             * @default Series
             */
            type: string;
            /** Country */
            country: string;
            /** Status */
            status: string;
            /** Release Year */
            release_year: number;
            /** Trailer Url */
            trailer_url?: string | null;
            /**
             * Feature Type
             * @default TRAILER
             */
            feature_type: string | null;
            /** Cast */
            cast?: string | null;
            /** Drive Link */
            drive_link?: string | null;
            /** Mega Link */
            mega_link?: string | null;
            /** Mediafire Link */
            mediafire_link?: string | null;
            /** Pixeldrain Link */
            pixeldrain_link?: string | null;
            /**
             * Is Featured
             * @default false
             */
            is_featured: boolean;
            /**
             * Views Count
             * @default 0
             */
            views_count: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_featured_config_series_featured_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedConfigResponse"];
                };
            };
        };
    };
    update_featured_config_series_featured_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeaturedConfigCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hero_featured_series_hero_featured_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
        };
    };
    get_stats_series_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_recommendations_series_recommendations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_personalized_recommendations_series_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationSignals"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_series_series__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                search?: string;
                is_featured?: boolean;
                type?: string;
                status?: string;
                country?: string;
                release_year?: number;
                genre?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_series_series__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_series_by_ids_series_by_ids_get: {
        parameters: {
            query: {
                ids: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_series_detail_series__series_ident__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_ident: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_episodes_series__series_ident__episodes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_ident: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Episode"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_actors_actors__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
                gender?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_actor_actors__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_actor_actors__actor_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_actor_actors__actor_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actor_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActorCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Actor"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_actor_actors__actor_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                actor_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_featured_series_series__series_id__feature_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_series_series__series_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Series"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_series_series__series_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_episode_series__series_id__episodes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                series_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Episode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_episode_series_episodes__episode_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EpisodeCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Episode"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_episode_series_episodes__episode_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                episode_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_current_user_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
